#!/usr/bin/env bash

set -e;

[[ ${DEBUG:-0} -eq 1 ]] && set -x;

source "${NVM_DIR}/nvm.sh";

# Ensure locally configured versions are honored.
[ -f "${NVM_DIR}/.nvmrc" ] && [[ "$(cat "${NVM_DIR}/.nvmrc")" != "" ]] \
  && nvm use "$(cat "${NVM_DIR}/.nvmrc")" &> /dev/null;

# shellcheck disable=SC2068
$NODE_APP $@ || exit $?;

# Ensure that Node version changes persist between runs.
if [[ "$NODE_APP" == "nvm" ]] && [[ "$1" == "use" ]] && [[ $# -gt 1 ]]; then
  nvm current > "${NVM_DIR}/.nvmrc";
fi