name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-dependencies:
    name: Build dependency
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [docker/php, docker/node]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build ${{ matrix.context }}

  build:
    name: Build
    needs: [build-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Compose Build
        run: touch .env.local && docker compose build

  run:
    name: Run
    needs: [build-dependencies]
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    env:
      DEBUG: 1
      TTY: 0
    strategy:
      fail-fast: false
      matrix:
        script:
          - php --version
          - composer --version
          - symfony version
          - nvm --version
          - node --version
          - npm --version
    steps:
      - name: Install Docker Engine
        run: apt install -y curl && curl -fsSL https://get.docker.com -o- | sh
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test version
        run: export PATH="$PWD:$PATH" && ${{ matrix.script }}