name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [docker/php, docker/node]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build ${{ matrix.context }}

  run:
    name: Run
    needs: [build]
    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      TTY: 0
    strategy:
      fail-fast: false
      matrix:
        script:
          - php --version
          - composer --version
          - symfony version
          - nvm --version
          - node --version
          - npm --version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build application
        run: touch .env.local && docker compose build "$(echo "${{ matrix.script }}" | cut -d' ' -f1)"
      - name: Test version
        run: export PATH="$PWD:$PATH" && ${{ matrix.script }}