name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-dependencies:
    name: Build dependency
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [docker/php, docker/node]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build ${{ matrix.context }}

  run:
    name: Run
    needs: [build-dependencies]
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    env:
      DEBUG: 1
      TTY: 0
    strategy:
      matrix:
        script:
          - php --version
          - composer --version
          - symfony version
          - nvm --version
          - node --version
          - npm --version
    steps:
      - name: Install Docker Engine
        run: apt update && apt install -y curl && curl -fsSL https://get.docker.com -o- | sh
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test version
        run: export PATH="$PWD:$PATH" && ${{ matrix.script }}

  override:
    name: Override
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure override
        run: |
          set -eux;
          <<- YAML > docker-compose.override.yaml
          services:
            php:
              build:
                args:
                  PHP_VERSION: 8.0.0
          YAML
          cat docker-compose.override.yaml
      - name: Test PHP version override
        run: |
          set -eux;
          export PATH="$PWD:$PATH"
          [[ "$(php --version)" == "PHP 8.0.0"* ]] || exit 42;