name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [docker/php, docker/node]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build ${{ matrix.context }}

  run:
    name: Test executable versions
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: PHP
            script: php -v
          - name: Composer
            script: composer -v
          - name: Symfony CLI
            script: symfony version
          - name: NVM
            script: nvm -v
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: export PATH="$PWD:$PATH" && ${{ matrix.script }}